name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: 'true'

      - name: Build
        run: bun run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: bun changeset version && bun i --lockfile-only
          publish: bun changeset publish
          commit: 'ci release'
          title: 'ci release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Drizzle kit
        if: steps.changesets.outputs.published == 'true'
        run: bun run generate:migration

      - name: D1 Migrations
        if: steps.changesets.outputs.published == 'true'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: d1 migrations apply hexcuit --remote

      - name: Deploy to Cloudflare Workers
        if: steps.changesets.outputs.published == 'true'
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
          secrets: |
            API_KEY
            CORS_ORIGIN
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}

  canary:
    name: Canary Release
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.published != 'true'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: 'true'

      - name: Version Canary
        run: bun changeset version --snapshot canary && bun i --lockfile-only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: bun run build

      - name: Publish Canary
        run: bun changeset publish --tag canary --no-git-tag
